# Generated by Django 5.0.6 on 2026-06-14 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('color', models.CharField(help_text='A CSS color or gradient, e.g. #0a4f5c or linear-gradient(...)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Right-side image (no text baked in — text comes from the fields above)', null=True, upload_to='banners/')),
                ('gradient', models.CharField(default='linear-gradient(135deg,#04323b,#0e7d8a 55%,#7fd6c9)', help_text='Fallback background if no image is uploaded', max_length=200)),
                ('btn1_text', models.CharField(blank=True, default='Design yours now', max_length=40)),
                ('btn1_link', models.CharField(blank=True, default='/studio/', help_text='Path or URL, e.g. /studio/', max_length=200)),
                ('btn2_text', models.CharField(blank=True, default='Browse collections', max_length=40)),
                ('btn2_link', models.CharField(blank=True, default='/collections/', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BeforeAfter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('before_image', models.ImageField(upload_to='beforeafter/')),
                ('after_image', models.ImageField(upload_to='beforeafter/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Before / after',
                'verbose_name_plural': 'Before / after',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('excerpt', models.CharField(help_text='One-line summary shown on the card', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('body', models.TextField(help_text="Supports **bold**, *italic*, blank-line paragraphs and '- ' bullet lists")),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Collection category',
                'verbose_name_plural': 'Collection categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube link (optional)')),
                ('story', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Customer story',
                'verbose_name_plural': 'Customer stories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Embellishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='studio/stickers/')),
                ('width', models.PositiveIntegerField(default=70, help_text='Default on-canvas width (px)')),
                ('height', models.PositiveIntegerField(default=70, help_text='Default on-canvas height (px)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Embellishment / sticker',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quote', 'B2B quote'), ('contact', 'Contact message')], default='contact', max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('segment', models.CharField(blank=True, max_length=80)),
                ('quantity', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('done', 'Completed')], default='received', max_length=12)),
                ('customer_name', models.CharField(blank=True, max_length=120)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PortraitShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('key', models.CharField(choices=[('square', 'Square'), ('heart', 'Heart'), ('circle', 'Circle'), ('topwave', 'Top wave'), ('oval', 'Oval')], default='square', help_text='Coded outline used to cut the photo (fixed in code)', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Riou Ocean Glass', max_length=80)),
                ('tagline', models.CharField(default='Printed Glass Studio', max_length=120)),
                ('phone', models.CharField(default='+230 5 123 4567', max_length=40)),
                ('whatsapp', models.CharField(default='23051234567', help_text='Digits only, e.g. 23051234567', max_length=40)),
                ('email', models.EmailField(default='hello@riouoceanglass.mu', max_length=254)),
                ('address', models.TextField(default='Royal Road, Curepipe, Mauritius')),
                ('map_embed', models.URLField(blank=True, default='https://www.google.com/maps?q=Mauritius&output=embed', help_text='Google Maps embed URL (Share → Embed a map → copy the src)')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com')),
                ('instagram', models.URLField(blank=True, default='https://instagram.com')),
                ('tiktok', models.URLField(blank=True, default='https://tiktok.com')),
                ('youtube', models.URLField(blank=True, default='https://youtube.com')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='BackgroundShapeDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_cm', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this shape at this size', max_digits=8)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='store.backgroundshape')),
            ],
            options={
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='studio/backgrounds/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('shape', models.ForeignKey(blank=True, help_text='Set automatically from the chosen size', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bg_images', to='store.backgroundshape')),
                ('dimension', models.ForeignKey(help_text='The exact size this image is made for', on_delete=django.db.models.deletion.CASCADE, related_name='bg_images', to='store.backgroundshapedimension')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(help_text='Frame graphic (transparent centre)', upload_to='studio/bgframes/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('shape', models.ForeignKey(blank=True, help_text='Set automatically from the chosen size', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='store.backgroundshape')),
                ('dimension', models.ForeignKey(help_text='The exact size this frame is made for', on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='store.backgroundshapedimension')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='store.collectioncategory')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CollectionDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_cm', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='store.collection')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.collection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('detail', models.CharField(blank=True, max_length=120)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('design', models.JSONField(blank=True, null=True)),
                ('render', models.ImageField(blank=True, null=True, upload_to='orders/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='PortraitShapeDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_cm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('height_cm', models.DecimalField(decimal_places=1, max_digits=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='store.portraitshape')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortraitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='studio/portraitimages/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('portrait_shape', models.ForeignKey(blank=True, help_text='Set automatically from the chosen size', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.portraitshape')),
                ('dimension', models.ForeignKey(help_text='The portrait shape + size this image is made for', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.portraitshapedimension')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortraitFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='studio/portraitframes/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('portrait_shape', models.ForeignKey(blank=True, help_text='Set automatically from the chosen size', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='store.portraitshape')),
                ('dimension', models.ForeignKey(help_text='The portrait shape + size this frame is made for', on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='store.portraitshapedimension')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ptype', models.CharField(choices=[('none', 'Ready-made'), ('partial', 'Personalize'), ('full', 'Full design')], default='none', max_length=10)),
                ('variant', models.CharField(choices=[('fixed', 'Fixed size'), ('multi', 'Multiple sizes')], default='fixed', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('motif', models.CharField(default='🌊', max_length=8)),
                ('gradient', models.CharField(default='linear-gradient(135deg,#0a4f5c,#7fd6c9)', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField(blank=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.productcategory')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuration', max_length=120)),
                ('design', models.JSONField(blank=True, help_text='Serialized studio design', null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Optional fixed price (else the shape/size base price applies)', max_digits=8, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
