# Generated by Django 5.0.6 on 2026-06-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab icon (square PNG, e.g. 512×512)', null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo_dark',
            field=models.ImageField(blank=True, help_text='Logo for DARK mode (PNG, transparent background)', null=True, upload_to='logo/'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='logo_light',
            field=models.ImageField(blank=True, help_text='Logo for LIGHT mode (PNG, transparent background)', null=True, upload_to='logo/'),
        ),
    ]
