# Generated by Django 5.0.14 on 2026-07-08 06:33 — hand-edited to preserve data.
#
# IMPORTANT: this migration may run against a LIVE production database that already
# has real Products created with the old `ptype` field ("none"/"partial"/"full").
# We map those to the new `product_type` ("fixed"/"personalise") BEFORE dropping the
# old columns, so existing products keep their correct type automatically instead of
# silently resetting to "fixed".

from django.db import migrations, models


def backfill_product_type(apps, schema_editor):
    Product = apps.get_model("store", "product")
    MAP = {"none": "fixed", "partial": "personalise", "full": "personalise"}
    for p in Product.objects.all():
        old = getattr(p, "ptype", "none")
        p.product_type = MAP.get(old, "fixed")
        p.save(update_fields=["product_type"])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_seed_studio_shapes'),
    ]

    operations = [
        # 1) Add the new field first (safe default so the column exists for every row).
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('personalise', 'Personalise')], default='fixed', help_text='Fixed: buy directly. Personalise: customer must use the studio (configs); no direct Add to cart.', max_length=12),
        ),
        # 2) Carry over each existing product's real type before the old columns disappear.
        migrations.RunPython(backfill_product_type, migrations.RunPython.noop),
        # 3) Now it's safe to drop the old fields.
        migrations.RemoveField(
            model_name='collection',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ptype',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
        migrations.CreateModel(
            name='FrameStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(help_text='Photo of the stand', upload_to='studio/framestands/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('frames', models.ManyToManyField(blank=True, help_text='Tick every Background Frame this stand fits', related_name='stands', to='store.backgroundframe')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
